version: '3.8'

networks:
  nuxt-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run dev'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - nuxt-network
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - nuxt-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
      
volumes:
  mysql_data:

